package admin

import (
	"encoding/json"
	"strings"
)

// -----------------------------------------------------------------------------
// Jump-Start: generated .vscode/settings.json
//
// When CreateSprout copies the repo, paths matching ".vscode/settings.json" are not taken
// verbatim from the template: we replace the whole file so each sprout gets:
//   - window.title — "{AppName} - {vscodeWindowTitleSuffix}"
//   - peacock.color + workbench.colorCustomizations derived from JumpStartConfig.PrimaryColor
//
// How to extend (new keys will land here soon):
//
//   1. Top-level VS Code keys (e.g. editor.*): add fields to jumpstartVSCodeSettingsRoot below,
//      or append to the map inside jumpstartVSCodeSettingsRoot after calling json.Marshal-safe API.
//
//   2. Workbench colors only: add entries in jumpstartWorkbenchColorCustomizations — group related
//      keys with blank-line comment blocks so the map stays navigable.
//
//   3. Keep behaviour aligned with the template repo’s `.vscode/settings.json` when you change
//      defaults here, so cloning vs Jump-Start produce the same baseline UX.
//
// Reference: https://code.visualstudio.com/docs/getstarted/settings
// Theme color IDs: https://code.visualstudio.com/api/references/theme-color
// -----------------------------------------------------------------------------

const (
	// vscodeWindowTitleSuffix appears after AppName in window.title ("{AppName} - {suffix}").
	vscodeWindowTitleSuffix = "Cursor"

	// vscodeSettingsFilePreamble is valid JSONC (VS Code / Cursor accept // comments).
	vscodeSettingsFilePreamble = "// Generated by Jump-Start — do not edit by hand in sprouts; " +
		"change generators in internal/admin/jumpstart_vscode.go (see file comment block).\n\n"
)

func jumpstartWindowTitle(cfg JumpStartConfig) string {
	return strings.TrimSpace(cfg.AppName) + " - " + vscodeWindowTitleSuffix
}

func jumpstartVSCodeSettingsJSON(cfg JumpStartConfig) ([]byte, error) {
	root := jumpstartVSCodeSettingsRoot(cfg)
	return json.MarshalIndent(root, "", "\t")
}

func jumpstartVSCodeSettingsRoot(cfg JumpStartConfig) map[string]any {
	primary := normalizeHexColor(cfg.PrimaryColor)

	dark := darkenHex(primary, 0.12) // status bar / title bar / peacock seed

	return map[string]any{
		// --- Top-level workspace keys (add more entries here if needed) ---
		"window.title": jumpstartWindowTitle(cfg),
		"peacock.color": dark,

		"workbench.colorCustomizations": jumpstartWorkbenchColorCustomizations(primary, dark),
	}
}

// jumpstartTemplateWorkbenchColorKeys is the full key set from the template repo
// `.vscode/settings.json`. Jump-Start must emit every key; only values that depend on
// PrimaryColor (and window.title) differ per sprout.
var jumpstartTemplateWorkbenchColorKeys = []string{
	"activityBar.activeBackground",
	"activityBar.background",
	"activityBar.foreground",
	"activityBar.inactiveForeground",
	"activityBarBadge.background",
	"activityBarBadge.foreground",
	"scrollbarSlider.activeBackground",
	"scrollbarSlider.background",
	"scrollbarSlider.hoverBackground",
	"statusBar.background",
	"statusBar.foreground",
	"statusBarItem.hoverBackground",
	"statusBarItem.remoteBackground",
	"statusBarItem.remoteForeground",
	"terminal.selectionBackground",
	"terminal.selectionForeground",
	"titleBar.activeBackground",
	"titleBar.activeForeground",
	"titleBar.inactiveBackground",
	"titleBar.inactiveForeground",
	"activityBar.border",
	"auxiliarySideBar.border",
	"panelTitle.border",
	"terminal.border",
	"commandCenter.border",
	"sash.hoverBorder",
	"sideBarSectionHeader.border",
	"secondarySideBar.border",
	"editorGroupHeader.border",
	"panel.border",
	"sideBar.border",
	"statusBar.border",
	"titleBar.border",
	"editor.border",
	"editorGroup.border",
}

func jumpstartWorkbenchColorCustomizations(primary, dark string) map[string]string {
	mid := primary
	badgeBg := lightenHex(primary, 0.35)

	selBg := terminalSelectionBackgroundHex(primary)

	out := map[string]string{
		// --- Activity bar (Peacock) — brand colors from PrimaryColor ---
		"activityBar.activeBackground":   mid,
		"activityBar.background":           mid,
		"activityBar.foreground":           "#15202b",
		"activityBar.inactiveForeground":   "#15202b99",
		"activityBarBadge.background":      badgeBg,
		"activityBarBadge.foreground":      "#15202b",

		// --- Scrollbars (fixed; template baseline) ---
		"scrollbarSlider.activeBackground": "#78716c80",
		"scrollbarSlider.background":         "#78716c40",
		"scrollbarSlider.hoverBackground":    "#78716c60",

		// --- Status bar / title bar — brand backgrounds, fixed light foregrounds ---
		"statusBar.background":             dark,
		"statusBar.foreground":             "#e7e7e7",
		"statusBarItem.hoverBackground":    mid,
		"statusBarItem.remoteBackground":   dark,
		"statusBarItem.remoteForeground":   "#e7e7e7",
		"titleBar.activeBackground":        dark,
		"titleBar.activeForeground":        "#e7e7e7",
		"titleBar.inactiveBackground":      dark + "99",
		"titleBar.inactiveForeground":      "#e7e7e799",

		// --- Terminal ---
		"terminal.selectionBackground": selBg,
		"terminal.selectionForeground": "#1c1917",

		// --- Sash (panel splits) ---
		"sash.hoverBorder": mid,

		// --- Panel separators (fixed white; template baseline) ---
		"activityBar.border":            "#ffffff",
		"auxiliarySideBar.border":       "#ffffff",
		"panelTitle.border":             "#ffffff",
		"terminal.border":               "#ffffff",
		"commandCenter.border":          "#e7e7e799",
		"sideBarSectionHeader.border":   "#ffffff",
		"secondarySideBar.border":         "#ffffff",
		"editorGroupHeader.border":        "#ffffff",
		"panel.border":                  "#ffffff",
		"sideBar.border":                "#ffffff",
		"statusBar.border":              "#ffffff",
		"titleBar.border":               "#ffffff",
		"editor.border":                 "#ffffff",
		"editorGroup.border":            "#ffffff",
	}

	// sash.hoverBorder set twice above — remove duplicate key issue by only setting once
	out["sash.hoverBorder"] = mid

	return out
}

func normalizeHexColor(raw string) string {
	s := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(raw), "#"))
	if s == "" {
		return "#f97316"
	}
	if len(s) == 3 {
		s = string([]byte{s[0], s[0], s[1], s[1], s[2], s[2]})
	}
	if len(s) < 6 {
		return "#f97316"
	}
	return "#" + s[:6]
}

func terminalSelectionBackgroundHex(primaryFull string) string {
	body := strings.TrimPrefix(primaryFull, "#")
	if len(body) != 6 {
		return "#f9731640"
	}
	return "#" + body + "40"
}
