package admin

import (
	"encoding/json"
	"strings"
)

// -----------------------------------------------------------------------------
// Jump-Start: generated .vscode/settings.json
//
// When CreateSprout copies the repo, paths matching ".vscode/settings.json" are not taken
// verbatim from the template: we replace the whole file so each sprout gets:
//   - window.title — "{AppName} - {vscodeWindowTitleSuffix}"
//   - peacock.color + workbench.colorCustomizations derived from JumpStartConfig.PrimaryColor
//
// How to extend (new keys will land here soon):
//
//   1. Top-level VS Code keys (e.g. editor.*): add fields to jumpstartVSCodeSettingsRoot below,
//      or append to the map inside jumpstartVSCodeSettingsRoot after calling json.Marshal-safe API.
//
//   2. Workbench colors only: add entries in jumpstartWorkbenchColorCustomizations — group related
//      keys with blank-line comment blocks so the map stays navigable.
//
//   3. Region borders + title bar text follow ~/.claude/skills/vscode-region-borders/
//      (inner #ffffff, outer #d3d3d3, titleBar foreground #ffffff). Only real theme-color
//      IDs — no editor.border / secondarySideBar.border / auxiliarySideBar.border.
//
// Reference: https://code.visualstudio.com/docs/getstarted/settings
// Theme color IDs: https://code.visualstudio.com/api/references/theme-color
// -----------------------------------------------------------------------------

const (
	// vscodeWindowTitleSuffix appears after AppName in window.title ("{AppName} - {suffix}").
	vscodeWindowTitleSuffix = "Cursor"

	// Region borders (vscode-region-borders skill defaults for dark themes).
	vscodeBorderInner              = "#ffffff"
	vscodeBorderOuter              = "#d3d3d3"
	vscodeTitleBarForeground       = "#ffffff"
	vscodeTitleBarInactiveForeground = "#ffffff99"
	vscodeCommandCenterBorder      = "#ffffff99"

	// vscodeSettingsFilePreamble is valid JSONC (VS Code / Cursor accept // comments).
	vscodeSettingsFilePreamble = "// Generated by Jump-Start — do not edit by hand in sprouts; " +
		"change generators in internal/admin/jumpstart_vscode.go (see file comment block).\n\n"
)

func jumpstartWindowTitle(cfg JumpStartConfig) string {
	return strings.TrimSpace(cfg.AppName) + " - " + vscodeWindowTitleSuffix
}

func jumpstartVSCodeSettingsJSON(cfg JumpStartConfig) ([]byte, error) {
	root := jumpstartVSCodeSettingsRoot(cfg)
	return json.MarshalIndent(root, "", "\t")
}

func jumpstartVSCodeSettingsRoot(cfg JumpStartConfig) map[string]any {
	primary := normalizeHexColor(cfg.PrimaryColor)

	dark := darkenHex(primary, 0.12) // status bar / title bar / peacock seed

	return map[string]any{
		// --- Top-level workspace keys (add more entries here if needed) ---
		"window.title": jumpstartWindowTitle(cfg),
		"peacock.color": dark,

		"workbench.colorCustomizations": jumpstartWorkbenchColorCustomizations(primary, dark),
	}
}

// jumpstartTemplateWorkbenchColorKeys is the full key set from the template repo
// `.vscode/settings.json`. Jump-Start must emit every key; only values that depend on
// PrimaryColor (and window.title) differ per sprout.
var jumpstartTemplateWorkbenchColorKeys = []string{
	"activityBar.activeBackground",
	"activityBar.background",
	"activityBar.foreground",
	"activityBar.inactiveForeground",
	"activityBarBadge.background",
	"activityBarBadge.foreground",
	"scrollbarSlider.activeBackground",
	"scrollbarSlider.background",
	"scrollbarSlider.hoverBackground",
	"statusBar.background",
	"statusBar.foreground",
	"statusBarItem.hoverBackground",
	"statusBarItem.remoteBackground",
	"statusBarItem.remoteForeground",
	"terminal.selectionBackground",
	"terminal.selectionForeground",
	"titleBar.activeBackground",
	"titleBar.activeForeground",
	"titleBar.inactiveBackground",
	"titleBar.inactiveForeground",
	"activityBar.border",
	"sideBarSectionHeader.border",
	"editorGroupHeader.tabsBorder",
	"editorGroupHeader.border",
	"panel.border",
	"panelTitle.border",
	"terminal.border",
	"sideBar.border",
	"editorGroup.border",
	"statusBar.border",
	"titleBar.border",
	"commandCenter.border",
	"sash.hoverBorder",
}

func jumpstartWorkbenchColorCustomizations(primary, dark string) map[string]string {
	mid := primary
	badgeBg := lightenHex(primary, 0.35)

	selBg := terminalSelectionBackgroundHex(primary)

	out := map[string]string{
		// --- Activity bar (Peacock) — brand colors from PrimaryColor ---
		"activityBar.activeBackground":   mid,
		"activityBar.background":           mid,
		"activityBar.foreground":           "#15202b",
		"activityBar.inactiveForeground":   "#15202b99",
		"activityBarBadge.background":      badgeBg,
		"activityBarBadge.foreground":      "#15202b",

		// --- Scrollbars (fixed; template baseline) ---
		"scrollbarSlider.activeBackground": "#78716c80",
		"scrollbarSlider.background":         "#78716c40",
		"scrollbarSlider.hoverBackground":    "#78716c60",

		// --- Status bar / title bar — brand backgrounds, fixed light foregrounds ---
		"statusBar.background":             dark,
		"statusBar.foreground":             "#e7e7e7",
		"statusBarItem.hoverBackground":    mid,
		"statusBarItem.remoteBackground":   dark,
		"statusBarItem.remoteForeground":   "#e7e7e7",
		"titleBar.activeBackground":        dark,
		"titleBar.activeForeground":        vscodeTitleBarForeground,
		"titleBar.inactiveBackground":      dark + "99",
		"titleBar.inactiveForeground":      vscodeTitleBarInactiveForeground,

		// --- Terminal ---
		"terminal.selectionBackground": selBg,
		"terminal.selectionForeground": "#1c1917",

		// --- Inner region borders (#ffffff) ---
		"activityBar.border":             vscodeBorderInner,
		"sideBarSectionHeader.border":    vscodeBorderInner,
		"editorGroupHeader.tabsBorder":   vscodeBorderInner,
		"editorGroupHeader.border":       vscodeBorderInner,
		"panel.border":                   vscodeBorderInner,
		"panelTitle.border":              vscodeBorderInner,
		"terminal.border":                vscodeBorderInner,
		"commandCenter.border":           vscodeCommandCenterBorder,

		// --- Outer region borders (#d3d3d3) ---
		"sideBar.border":                 vscodeBorderOuter,
		"editorGroup.border":             vscodeBorderOuter,
		"statusBar.border":               vscodeBorderOuter,
		"titleBar.border":                vscodeBorderOuter,

		// --- Sash (panel drag handles) ---
		"sash.hoverBorder": mid,
	}

	return out
}

func normalizeHexColor(raw string) string {
	s := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(raw), "#"))
	if s == "" {
		return "#f97316"
	}
	if len(s) == 3 {
		s = string([]byte{s[0], s[0], s[1], s[1], s[2], s[2]})
	}
	if len(s) < 6 {
		return "#f97316"
	}
	return "#" + s[:6]
}

func terminalSelectionBackgroundHex(primaryFull string) string {
	body := strings.TrimPrefix(primaryFull, "#")
	if len(body) != 6 {
		return "#f9731640"
	}
	return "#" + body + "40"
}
