package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"megane/internal/datamodeling"
)

// GoStruct generates a Go source file with the LLMOutput struct.
// slug is the file type slug (e.g. "invoice").
// Only fields with Override.Included=true are emitted.
// Returns formatted Go source (go/format.Source applied).
func GoStruct(slug string, fields []datamodeling.FieldRow) ([]byte, error) {
	var b bytes.Buffer

	structName := camelCase(slug) + "Analysis"

	b.WriteString("// Code generated by jump-starter build-from-schema. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Re-generate with: POST /api/admin/datamodeling/types/<id>/build/apply\n"))
	b.WriteString("package models\n\n")

	b.WriteString(fmt.Sprintf("type %s struct {\n", structName))

	// Sort fields: critical -> high -> normal, then alphabetical
	var included []datamodeling.FieldRow
	for _, f := range fields {
		if f.Override.Included {
			included = append(included, f)
		}
	}

	sort.Slice(included, func(i, j int) bool {
		e1 := emphasisWeight(included[i].Override.Emphasis)
		e2 := emphasisWeight(included[j].Override.Emphasis)
		if e1 != e2 {
			return e1 > e2
		}
		return included[i].SchemaField.Name < included[j].SchemaField.Name
	})

	for _, f := range included {
		goName := camelCase(f.SchemaField.Name)
		goType := mapType(f.SchemaField.Type, f.SchemaField.Description)

		desc := strings.TrimSpace(f.SchemaField.Description)
		if f.Override.Rules != "" {
			if desc != "" {
				desc += " "
			}
			desc += f.Override.Rules
		}

		if f.SchemaField.Type == "date" {
			if desc != "" {
				desc += " "
			}
			desc += "(ISO 8601)"
		}

		jsonTag := f.SchemaField.Name
		if !f.Override.Required {
			jsonTag += ",omitempty"
		}

		b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\" description:\"%s\"`", goName, goType, jsonTag, escapeQuotes(desc)))
		if f.SchemaField.Type == "array" || f.SchemaField.Type == "object" {
			b.WriteString(" // TODO: replace with typed struct when shape is known")
		}
		b.WriteString("\n")
	}

	b.WriteString("}\n\n")
	b.WriteString(fmt.Sprintf("func (%s) SchemaName() string { return %q }\n", structName, slug+"_analysis"))

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("format error: %w", err)
	}
	return formatted, nil
}

func emphasisWeight(e string) int {
	switch e {
	case "critical":
		return 3
	case "high":
		return 2
	case "normal":
		return 1
	default:
		return 1
	}
}

func camelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func mapType(schemaType, desc string) string {
	switch schemaType {
	case "string":
		return "string"
	case "number":
		if strings.Contains(strings.ToLower(desc), "decimal") || strings.Contains(strings.ToLower(desc), "float") {
			return "float64"
		}
		return "float64" // default to float64 as heuristic
	case "boolean":
		return "bool"
	case "date":
		return "string"
	case "array":
		return "[]map[string]any"
	case "object":
		return "map[string]any"
	default:
		return "string"
	}
}

func escapeQuotes(s string) string {
	return strings.ReplaceAll(s, `"`, `\"`)
}
